#!/bin/bash

wget -q --spider http://tts.baidu.com
if [ $? != 0 ]; then
	mplayer -ao alsa -really-quiet -noconsolecontrols $HOME/bdtts/audio/net.mp3 
	exit
fi


say() {
local IFS=+;
mplayer -ao alsa -really-quiet -noconsolecontrols "http://tts.baidu.com/text2audio?lan=zh&ie=UTF-8&spd=5&text=$*";
}
say $*
