#!/bin/bash

# Must install wget and mplayer

wget -q --spider http://tts.baidu.com
if [ $? != 0 ]; then
	mplayer -ao alsa -really-quiet -noconsolecontrols $HOME/bdtts/audio/net.mp3 
	exit
fi

if [ "$1" = "-s" ];then
	mplayer -ao alsa -really-quiet -noconsolecontrols "http://tts.baidu.com/text2audio?lan=zh&ie=UTF-8&spd=5&text=$2"
elif [ "$1" = "-d" ];then
	wget -c "http://tts.baidu.com/text2audio?lan=zh&ie=UTF-8&spd=5&text=$2" -O /tmp/`date +%T`.mp3 
else
	mplayer -ao alsa -really-quiet -noconsolecontrols "http://tts.baidu.com/text2audio?lan=zh&ie=UTF-8&spd=5&text=$*"
	wget -c "http://tts.baidu.com/text2audio?lan=zh&ie=UTF-8&spd=5&text=$*" -O /tmp/`date +%T`.mp3
fi
