#!/bin/bash

wget -q --spider http://tts.baidu.com
if [ $? != 0 ]; then
	mpg123 -q $HOME/bdtts/audio/net.mp3 
	exit
fi

if [ "$1" = "-s" ];then
	mpg123 -q "http://tts.baidu.com/text2audio?cuid=baiduid&lan=zh&ctp=1&pdt=311&spd=5&tex=$2"
elif [ "$1" = "-d" ];then
	wget -c "http://tts.baidu.com/text2audio?cuid=baiduid&lan=zh&ctp=1&pdt=311&spd=5&tex=$2" -O /tmp/`date +%T`.mp3 
else
	mpg123 -q "http://tts.baidu.com/text2audio?cuid=baiduid&lan=zh&ctp=1&pdt=311&spd=5&tex=$*"
	wget -c "http://tts.baidu.com/text2audio?cuid=baiduid&lan=zh&ctp=1&pdt=311&spd=5&tex=$*" -O /tmp/`date +%T`.mp3
fi
