#!/bin/bash

# Must install wget mplayer translate-shell

wget -q --spider http://tts.baidu.com
if [ $? != 0 ];then
	mplayer -ao alsa -really-quiet -noconsolecontrols $HOME/mytts/audio/net.mp3
	exit
fi

if [ $1 = "-g" ];then
	if [ "$2" = "-s" ];then
		trans -b -speak $3
	elif [ "$2" = "-d" ];then
		trans -b $3 -download-audio-as /tmp/`date +%T`.mp3
	else
		trans -b -speak $2 -download-audio-as /tmp/`date +%T`.mp3
	fi
elif [ "$1" = "-b" ];then
	if [ "$2" = "-s" ];then
		mplayer -ao alsa -really-quiet -noconsolecontrols "http://tts.baidu.com/text2audio?idx=1&cuid=baidu_speech_demo&cod=2&lan=zh&ctp=1&pdt=1&spd=4&per=5&vol=5&pit=5&tex=$3"
	elif [ "$2" = "-d" ];then
		wget -c "http://tts.baidu.com/text2audio?idx=1&cuid=baidu_speech_demo&cod=2&lan=zh&ctp=1&pdt=1&spd=4&per=5&vol=5&pit=5&tex=$3" -O /tmp/`date +%T`.mp3
	else
		mplayer -ao alsa -really-quiet -noconsolecontrols "http://tts.baidu.com/text2audio?idx=1&cuid=baidu_speech_demo&cod=2&lan=zh&ctp=1&pdt=1&spd=4&per=5&vol=5&pit=5&tex=$2"
		wget -c "http://tts.baidu.com/text2audio?idx=1&cuid=baidu_speech_demo&cod=2&lan=zh&ctp=1&pdt=1&spd=4&per=5&vol=5&pit=5&tex=$2" -O /tmp/`date +%T`.mp3
	fi
fi
