#!/bin/bash

# Must install wget and mplayer

wget -q --spider http://tts.baidu.com

if [ $? != 0 ];then
	mplayer -really-quiet -noconsolecontrols $HOME/mytts/audio/net.mp3
	exit
fi

if [ $1 = "-g" ];then
	if [ "$2" = "-s" ];then
		mplayer -really-quiet -noconsolecontrols "http://translate.google.cn/translate_tts?ie=UTF-8&client=tw-ob&tl=zh-CN&q=$3"
	elif [ "$2" = "-d" ];then
		wget -q -U Mozilla -O /tmp/`date +%T`.mp3 "http://translate.google.cn/translate_tts?ie=UTF-8&client=tw-ob&tl=zh-CN&q=$3"
	else
		mplayer -really-quiet -noconsolecontrols "http://translate.google.cn/translate_tts?ie=UTF-8&client=tw-ob&tl=zh-CN&q=$2"
		wget -q -U Mozilla -O /tmp/`date +%T`.mp3 "http://translate.google.cn/translate_tts?ie=UTF-8&client=tw-ob&tl=zh-CN&q=$2"
	fi
elif [ "$1" = "-b" ];then
	if [ "$2" = "-s" ];then
		mplayer -really-quiet -noconsolecontrols "http://tts.baidu.com/text2audio?idx=1&cuid=baidu_speech_demo&cod=2&lan=zh&ctp=1&pdt=1&spd=4&per=5&vol=5&pit=5&tex=$3"
	elif [ "$2" = "-d" ];then
		wget -q -U Mozilla -O /tmp/`date +%T`.mp3 "http://tts.baidu.com/text2audio?idx=1&cuid=baidu_speech_demo&cod=2&lan=zh&ctp=1&pdt=1&spd=4&per=5&vol=5&pit=5&tex=$3"
	else
		mplayer -really-quiet -noconsolecontrols "http://tts.baidu.com/text2audio?idx=1&cuid=baidu_speech_demo&cod=2&lan=zh&ctp=1&pdt=1&spd=4&per=5&vol=5&pit=5&tex=$2"
		wget -q -U Mozilla -O /tmp/`date +%T`.mp3 "http://tts.baidu.com/text2audio?idx=1&cuid=baidu_speech_demo&cod=2&lan=zh&ctp=1&pdt=1&spd=4&per=5&vol=5&pit=5&tex=$2"
	fi
fi
